stages:
    - build
    - package
  
extension:
    image: node:10
    stage: build
    only:
        - tags
    script:
        - npm i -g gulp
        - npm i
        - npm audit fix
        - gulp bundle --ship
        - gulp package-solution --ship
        - mv ./sharepoint/solution/scrollToTop.sppkg ././scrollToTop.sppkg
    artifacts:
        paths:
        - scrollToTop.sppkg
    allow_failure: false

bash:
    image: node:latest
    stage: package
    dependencies:
        - extension
    only:
        - tags
    script:
        - apt-get update -y && apt-get install p7zip-full -y
        - 7z a scrollToTop-setup-bash.zip *.sh
        - 7z a scrollToTop-setup-bash.zip scrollToTop.sppkg
    artifacts:
        paths:
        - scrollToTop-setup-bash.zip
    allow_failure: false

powershell:
    image: node:latest
    stage: package
    dependencies:
        - extension
    only:
        - tags
    script:
        - apt-get update -y && apt-get install p7zip-full -y
        - 7z a scrollToTop-setup-powershell.zip *.ps1
        - 7z a scrollToTop-setup-powershell.zip scrollToTop.sppkg
    artifacts:
        paths:
        - scrollToTop-setup-powershell.zip
    allow_failure: false

changelog:
    image: node:latest
    stage: package
    only:
        - master
    except:
        variables:
        - $CI_COMMIT_MESSAGE =~ /Update Changelog from CI/
    script:
        - npm install -g conventional-changelog-cli && npm install -g version && apt-get install git
        - mkdir repo && cd ./repo
        - git clone -b $CI_COMMIT_REF_NAME https://gitlab-runner:$CI_ACCESS_TOKEN@gitlab.lsonline.fr/$CI_PROJECT_PATH.git && git init &> /dev/null
        - cd ./$CI_PROJECT_NAME
        - conventional-changelog -p angular -i CHANGELOG.md -s && git add CHANGELOG.md && git pull
        - git config --global user.email "$GITLAB_USER_EMAIL"
        - git commit -m 'Update Changelog from CI' && git push origin $CI_COMMIT_REF_NAME &> /dev/null
