declare const styles: {
    templateRoot: string;
    slideRightIn10: string;
    slideRightIn20: string;
    slideRightIn40: string;
    slideLeftIn10: string;
    slideLeftIn20: string;
    slideLeftIn40: string;
    slideRightIn400: string;
    slideLeft400: string;
    slideUpIn20: string;
    slideUpIn10: string;
    slideDownIn20: string;
    slideDownIn10: string;
    slideRightOut40: string;
    slideLeftOut40: string;
    slideRightOut400: string;
    slideLeftOut400: string;
    slideUpOut20: string;
    slideUpOut10: string;
    slideDownOut20: string;
    slideDownOut10: string;
    scaleUp100: string;
    scaleDown100: string;
    scaleUp103: string;
    scaleDown98: string;
    fadeIn: string;
    fadeOut: string;
    rotate90: string;
    rotateN90: string;
};
export default styles;
